// Floor-specific map data for floor2

Object.assign(DATA, {
  "alchemist-kaelor": {
    title: "Alchemist",
    type: "NPC",
    category: "alchemist",
    floor: "floor2",
    coords: { x: -568, z: -293 },
    drops: ["N/A"],
    description: "Alchemist",
  },
  "assistant-alchimiste-kaelor": {
    title: "Assistant to the Alchemist",
    type: "NPC",
    category: "alchemist",
    floor: "floor2",
    coords: { x: -574, z: -299 },
    drops: ["N/A"],
    description: "Assistant to the Alchemist",
  },
  "cabinetmaker-kaelor": {
    title: "Cabinetmaker",
    type: "NPC",
    category: "lumberjack",
    floor: "floor2",
    coords: { x: -575, z: -293 },
    drops: ["N/A"],
    description: "Makes Wooden Boards and Acacia Wood Powder.",
  },
  "crushed-harpy-ring": {
    title: "Manufacturer of the Crushed Harpy Ring",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -618, z: 529 },
    drops: ["N/A"],
    description: "Crushed Harpy Ring Blacksmith.",
  },
  "flaming-harpy-ring": {
    title: "Manufacturer of the Ring of the Flaming Harpy",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -694, z: 205 },
    underground: true,
    drops: ["N/A"],
    description: "Flaming Harpy Ring Blacksmith.",
  },
  "drowned-harpy-ring": {
    title: "Manufacturer of the Ring of the Drowned Harpy",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -818, z: 98 },
    drops: ["N/A"],
    description: "Drowned Harpy Ring Blacksmith.",
  },
  "wild-gloves-manufacturer": {
    title: "Manufacturer of Wild Gloves",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -498, z: -746 },
    drops: ["N/A"],
    description: "Wild Gloves Blacksmith.",
  },
  "runic-necklace-manufacturer": {
    title: "Manufacturer of the Runic Necklace",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -38, z: 199 },
    drops: ["N/A"],
    description: "Runic Necklace Blacksmith.",
  },
  "corrupt-mask-manufacturer": {
    title: "Manufacturer of Corrupt Mask",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -713, z: -109 },
    drops: ["N/A"],
    description: "Corrupt Mask Blacksmith.",
  },
  "fierce-talisman-manufacturer": {
    title: "Manufacturer of the Fierce Talisman",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: 78, z: -71 },
    drops: ["N/A"],
    description: "Fierce Talisman Blacksmith.",
  },
  "local-farmer-kaelor": {
    title: "Local Farmer",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor2",
    coords: { x: -581, z: -273 },
    drops: ["N/A"],
    description: "Local Farmer - Buys Loot.",
  },
  "refaire-refaiter": {
    title: "Refaiter",
    type: "NPC",
    category: "refaire",
    floor: "floor2",
    coords: { x: 0, z: -355 },
    drops: ["N/A"],
    description: "Transforms Resources and Spider Threads to make useful strings in making Accessories.",
  },
  "impure-onyx-accessories-blacksmith": {
    title: "Impure Onyx Accessories Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -502, z: 334 },
    drops: ["N/A"],
    description: "Impure Onyx Accessories Blacksmith.",
  },
  "pure-onyx-accessories-blacksmith": {
    title: "Pure Onyx Accessories Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: 339, z: 505 },
    underground: true,
    drops: ["N/A"],
    description: "Pure Onyx Accessories Blacksmith.",
  },
  "bauxite-accessories-blacksmith": {
    title: "Bauxite Accessories Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -194, z: 20 },
    drops: ["N/A"],
    description: "Bauxite Accessories Blacksmith.",
  },
  "scrap-accessories-blacksmith": {
    title: "Scrap Accessories Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -777, z: 17 },
    drops: ["N/A"],
    description: "Scrap Accessories Blacksmith.",
  },
  "bull-and-bear-accessories-blacksmith": {
    title: "Bull & Bear Accessories Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: -602, z: -285 },
    drops: ["N/A"],
    description: "Bull & Bear Accessories Blacksmith",
  },
  "accessories-blacksmith-p2": {
    title: "Accessories Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor2",
    coords: { x: 111, z: -408 },
    drops: ["N/A"],
    description: "Accessories Blacksmith",
  },
  "bee-weapon-blacksmith": {
    title: "Bees Weapon Blacksmith",
    type: "NPC",
    category: "weaponsmith",
    floor: "floor2",
    coords: { x: 591, z: -700 },
    underground: true,
    drops: ["N/A"],
    description: "Bees Weapon Blacksmith",
  },
  "necrotic-weaponsmith": {
    title: "Necrotic Weaponsmith",
    type: "NPC",
    category: "weaponsmith",
    floor: "floor2",
    coords: { x: 727, z: 265 },
    underground: true,
    drops: ["N/A"],
    description: "Necrotic Weaponsmith",
  },
  "bee-armor-blacksmith": {
    title: "Bee Armor Blacksmith",
    type: "NPC",
    category: "armorBlacksmith",
    floor: "floor2",
    coords: { x: 591, z: -675 },
    underground: true,
    drops: ["N/A"],
    description: "Bee Armor Blacksmith",
  },
  "necromancer-armor-blacksmith": {
    title: "Blacksmith of Necromancer Armor",
    type: "NPC",
    category: "armorBlacksmith",
    floor: "floor2",
    coords: { x: 722, z: 264 },
    underground: true,
    drops: ["N/A"],
    description: "Necromancer Armor Blacksmith",
  },
  "necrotic-tool-blacksmith": {
    title: "Necrotic Tool Blacksmith",
    type: "NPC",
    category: "toolMerchants",
    floor: "floor2",
    coords: { x: 722, z: 268 },
    underground: true,
    drops: ["N/A"],
    description: "Necrotic Tool Blacksmith",
  },
  "pure-onyx-ingot-blacksmith": {
    title: "Pure Onyx Ingot Blacksmith",
    type: "NPC",
    category: "ingotBlacksmith",
    floor: "floor2",
    coords: { x: 868, z: -295 },
    drops: ["N/A"],
    description: "Pure Onyx Ingot Blacksmith",
  },
  "bauxite-ingot-impure-onyx-blacksmith": {
    title: "Blacksmith of Bauxite Ingots & Impure Onyx",
    type: "NPC",
    category: "ingotBlacksmith",
    floor: "floor2",
    coords: { x: 124, z: -385 },
    drops: ["N/A"],
    description: "Bauxite Ingots & Impure Onyx Blacksmith",
  },
  "accessories-merchant-kaelor": {
    title: "Accessories Merchant",
    type: "NPC",
    category: "accessoriesMerchants",
    floor: "floor2",
    coords: { x: -568, z: -287 },
    drops: ["N/A"],
    description: "Accessories Merchant",
  },
  "occult-amulet-merchant-taurus": {
    title: "Occult Amulet Merchant",
    type: "NPC",
    category: "occultMerchants",
    floor: "floor2",
    coords: { x: -351, z: 877 },
    underground: true,
    drops: ["N/A"],
    description: "Occult Amulet Merchant",
  },
  "occult-ringman-taurus": {
    title: "Occult Ringman",
    type: "NPC",
    category: "occultMerchants",
    floor: "floor2",
    coords: { x: -354, z: 882 },
    underground: true,
    drops: ["N/A"],
    description: "Occult Ringman",
  },
  "occult-artifact-merchant-brasier": {
    title: "Occult Artifact Merchant",
    type: "NPC",
    category: "occultMerchants",
    floor: "floor2",
    coords: { x: -321, z: 115 },
    underground: true,
    drops: ["N/A"],
    description: "Occult Artifact Merchant",
  },
  "equipment-merchant-kaelor": {
    title: "Equipment Merchant",
    type: "NPC",
    category: "equipmentMerchants",
    floor: "floor2",
    coords: { x: -576, z: -288 },
    drops: ["N/A"],
    description: "Sell Weapons and Consumables for newcomers.",
  },
  "savanna-tool-merchant": {
    title: "Savanna Tool Merchant",
    type: "NPC",
    category: "toolMerchants",
    floor: "floor2",
    coords: { x: -583, z: -286 },
    drops: ["N/A"],
    description: "Sell Tier 2 Tools; Savanna tools.",
  },
  "occult-bracelet-merchant-taurus": {
    title: "Occult Bracelet Merchant",
    type: "NPC",
    category: "occultMerchants",
    floor: "floor2",
    coords: { x: -343, z: 879 },
    underground: true,
    drops: ["N/A"],
    description: "Occult Bracelet Merchant",
  },
  "occult-gloves-merchant-taurus": {
    title: "Occult Gloves Merchant",
    type: "NPC",
    category: "occultMerchants",
    floor: "floor2",
    coords: { x: -345, z: 887 },
    underground: true,
    drops: ["N/A"],
    description: "Occult Gloves Merchant",
  },
  "miner-of-the-corner-urbus": {
    title: "Miner of the Corner",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor2",
    coords: { x: 129, z: -380 },
    drops: ["N/A"],
    description: "Miner of the Corner",
  },
  "Refauncher-urbus": {
    title: "Refauncher",
    type: "NPC",
    category: "keyBlacksmith",
    floor: "floor2",
    coords: { x: 2, z: -356 },
    drops: ["N/A"],
    description: "Transforms Resources and Spider Threads to make useful strings in making Accessories.",
  },
  "honeyed-loot-buyer": {
    title: "Honeyed Loot Buyer",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor2",
    coords: { x: 591, z: -690 },
    underground: true,
    drops: ["N/A"],
    description: "Honeyed Loot Buyer",
  },
  "harpies-loot-buyer": {
    title: "Harpies Loot Buyer",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor2",
    coords: { x: -568, z: -255 },
    drops: ["N/A"],
    description: "Harpies Loot Buyer",
  },
  "repreneur_de_butin_p2_marome": {
    title: "Sanctuary Loot Repreneur",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor2",
    coords: { x: 710, z: -277 },
    drops: ["N/A"],
    description: "Sells objects from the Sanctuary of Khesûn.",
  },
  "necrotic-loot-repreneur": {
    title: "Necrotic Loot Repreneur",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor2",
    coords: { x: 728, z: 268 },
    underground: true,
    drops: ["N/A"],
    description: "Sells Necrotic Loot.",
  },
  "bull-and-bear-loot-buyer": {
    title: "Bull & Bear Loot Buyer",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor2",
    coords: { x: 68, z: -343 },
    drops: ["N/A"],
    description: "Take back items from Bulls and Bears.",
  },
  "autel_des_deux_lunes": {
    title: "Altar of Two Moons",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 570, z: -470 },
    drops: ["N/A"],
    description: "A mysterious moonlit altar located at the heart of Map 2.",
  },
  "baie_des_monstres_ondoyante": {
    title: "Wavy Monster Bay",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -780, z: 171 },
    drops: ["N/A"],
    description: "A shoreline biome where monsters gather along restless waves.",
  },
  "baobab_millenaire": {
    title: "Millennial Baobab",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -88, z: -92 },
    drops: ["N/A"],
    description: "A giant ancient baobab tree standing watch over the area.",
  },
  "desert_des_crocs_argentes": {
    title: "Silver Fang Desert",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -372, z: -556 },
    drops: ["N/A"],
    description: "A harsh desert known for its silver sands and dangerous predators.",
  },
  "foret_des_ailes_d_emeraude": {
    title: "Emerald Wings Forest",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -550, z: 476 },
    drops: ["N/A"],
    description: "A vibrant forest filled with lush foliage and winged creatures.",
  },
  "foret_sucree": {
    title: "Sweet Forest",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 484, z: -665 },
    drops: ["N/A"],
    description: "A fragrant woodland alive with sweet flora and hidden paths.",
  },
  "grotte_de_taran": {
    title: "Taran Cave",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -316, z: -94 },
    underground: true,
    drops: ["N/A"],
    description: "A dark underground cave beneath Taran, home to hidden dangers.",
  },
  "kaelor": {
    title: "Kaelor",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -583, z: -264 },
    drops: ["N/A"],
    description: "A remote biome named Kaelor, known for its unusual terrain.",
  },
  "lac_des_taureaux": {
    title: "Lake of the Bulls",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 118, z: -68 },
    drops: ["N/A"],
    description: "A quiet lake surrounded by rugged scenery and wild beasts.",
  },
  "les_veines_de_sablemor": {
    title: "Sablemor Veins",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 225, z: 295 },
    underground: true,
    drops: ["N/A"],
    description: "Underground mineral veins near Sablemor, rich with rare ore.",
  },
  "maisons_des_ngangas": {
    title: "Nganga Houses",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -430, z: -428 },
    drops: ["N/A"],
    description: "A small settlement of Ngangas houses with mystic inhabitants.",
  },
  "marome": {
    title: "Marome",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 721, z: -281 },
    drops: ["N/A"],
    description: "A coastal enclave with tropical life and hidden secrets.",
  },
  "nid_de_brasier": {
    title: "Brazier Nest",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -581, z: 234 },
    underground: true,
    drops: ["N/A"],
    description: "A fiery underground nest where blazing creatures gather.",
  },
  "oasis_secret": {
    title: "Secret Oasis",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 798, z: 253 },
    drops: ["N/A"],
    description: "A hidden oasis tucked away in Map 2's desert regions.",
  },
  "ruche_de_melliona": {
    title: "Melliona's Hive",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 506, z: -724 },
    drops: ["N/A"],
    description: "The buzzing hive where Melliona's creatures gather.",
  },
  "sanctuaire_de_khesun": {
    title: "Sanctuary of Khesun",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -6, z: 181 },
    drops: ["N/A"],
    description: "A sacred sanctuary dedicated to the guardian Khesun.",
  },
  "taran": {
    title: "Taran",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -427, z: 272 },
    drops: ["N/A"],
    description: "A rugged region known for strong winds and sparse vegetation.",
  },
  "tombeau_du_necromancien": {
    title: "Necromancer's Tomb",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 721, z: 244 },
    underground: true,
    drops: ["N/A"],
    description: "An ancient tomb filled with necromantic energies.",
  },
  "tour_de_taurus": {
    title: "Taurus Tower",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: -160, z: 795 },
    drops: ["N/A"],
    description: "A towering spire watched over by Taurus.",
  },
  "urbus": {
    title: "Urbus",
    type: "Biome",
    category: "biomes",
    floor: "floor2",
    coords: { x: 64, z: -348 },
    drops: ["N/A"],
    description: "The town of Urbus, a key waypoint in the Map 2 region.",
  },
  "gardien_sanctuaire": {
    title: "Sanctuary Guardian",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor2",
    coords: { x: 0, z: 190 },
    underground: true,
    drops: ["N/A"],
    description: "A powerful boss guarding the sacred sanctuary.",
  },
  "magnus": {
    title: "Magnus",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor2",
    coords: { x: 228, z: 316 },
    underground: true,
    drops: ["N/A"],
    description: "A fearsome boss encountered underground in Map 2.",
  },
  "melisara": {
    title: "Melisara",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor2",
    coords: { x: 175, z: -409 },
    underground: true,
    drops: ["N/A"],
    description: "A dangerous boss lurking in the depths of Map 2.",
  },
  "morveth": {
    title: "Morveth",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor2",
    coords: { x: 583, z: -187 },
    underground: true,
    drops: ["N/A"],
    description: "A subterranean boss found deep below Map 2.",
  },
  "rugiboeuf": {
    title: "Rugiboeuf",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor2",
    coords: { x: -155, z: 571 },
    drops: ["N/A"],
    description: "A colossal boss roaming the northern reaches of Map 2.",
  },
  "velindra": {
    title: "Velindra",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor2",
    coords: { x: 800, z: 300 },
    underground: true,
    drops: ["N/A"],
    description: "A shadowy boss hidden beneath the surface.",
  },
  "winnie": {
    title: "Winnie",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor2",
    coords: { x: 578, z: -774 },
    drops: ["N/A"],
    description: "A rare boss found in the western areas of Map 2.",
  },
  "donjon_ruche_de_melliona": {
    title: "Melliona's Hive Dungeon",
    type: "Dungeon",
    category: "dungeons",
    floor: "floor2",
    coords: { x: 506, z: -724 },
    drops: ["N/A"],
    description: "A dungeon formed inside Melliona's Hive.",
  },
  "donjon_tombeau_du_necromancien": {
    title: "Necromancer's Tomb Dungeon",
    type: "Dungeon",
    category: "dungeons",
    floor: "floor2",
    coords: { x: 721, z: 244 },
    drops: ["N/A"],
    description: "A dungeon built within the Necromancer's Tomb.",
  },
  "fs_q_p1_la_facette_de_la_realite": {
    title: "The Facet of Reality",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 62, z: -428 },
    drops: ["N/A"],
    description: "A side quest about uncovering a hidden facet of reality.",
  },
  "fs_q_p2_a_la_recherche_des_ngangas": {
    title: "In Search of the Ngangas",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -585, z: -255 },
    drops: ["N/A"],
    description: "A side quest to locate the Ngangas people.",
  },
  "fs_q_p2_aide_a_la_cuisine": {
    title: "Kitchen Help",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -563, z: -255 },
    drops: ["N/A"],
    description: "A quest to assist with cooking and preparation tasks.",
  },
  "fs_q_p2_aider_yuko": {
    title: "Help Yuko",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -610, z: -245 },
    drops: ["N/A"],
    description: "A quest to help Yuko with an important task.",
  },
  "fs_q_p2_ca_pique_mais_ca_fait_du_bien": {
    title: "It Stings but Feels Good",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -577, z: -256 },
    drops: ["N/A"],
    description: "A quest that tests resilience through painful trials.",
  },
  "fs_q_p2_chemin_vers_urbus": {
    title: "Road to Urbus",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 135, z: -374 },
    drops: ["N/A"],
    description: "A quest guiding the player toward Urbus.",
  },
  "fs_q_p2_communication_avec_yaa": {
    title: "Talking With Yaa",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 743, z: -257 },
    drops: ["N/A"],
    description: "A quest focused on communicating with Yaa.",
  },
  "fs_q_p2_donjon_le_tombeau_oublie": {
    title: "Dungeon: The Forgotten Tomb",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 160, z: -312 },
    drops: ["N/A"],
    description: "A quest involving the forgotten tomb dungeon.",
  },
  "fs_q_p2_faconneur_de_cle_i": {
    title: "Key Smith I",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 160, z: -312 },
    drops: ["N/A"],
    description: "A quest about creating a key with a master smith.",
  },
  "fs_q_p2_hater_du_vert": {
    title: "Hating the Green",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -431, z: 279 },
    drops: ["N/A"],
    description: "A quest centered around a rivalry with the color green.",
  },
  "fs_q_p2_l_art_des_peaux": {
    title: "The Art of Hides",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 105, z: -392 },
    drops: ["N/A"],
    description: "A quest exploring how to work with animal hides.",
  },
  "fs_q_p2_l_art_des_plumes": {
    title: "The Art of Feathers",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 112, z: -391 },
    drops: ["N/A"],
    description: "A quest focused on collecting or crafting with feathers.",
  },
  "fs_q_p2_l_empreinte_des_seas": {
    title: "The Imprint of the Seas",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 620, z: -567 },
    drops: ["N/A"],
    description: "A quest tied to the legacy left by the seas.",
  },
  "fs_q_p2_l_epreuve_du_chasseur": {
    title: "The Hunter's Trial",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -202, z: -688 },
    drops: ["N/A"],
    description: "A hunting trial to prove your skills.",
  },
  "fs_q_p2_l_onyx_du_savoir": {
    title: "The Onyx of Knowledge",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 724, z: -301 },
    drops: ["N/A"],
    description: "A quest about recovering an onyx of knowledge.",
  },
  "fs_q_p2_la_philosophie_de_bushi": {
    title: "Bushi's Philosophy",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -41, z: 205 },
    drops: ["N/A"],
    description: "A philosophical quest inspired by Bushi teachings.",
  },
  "fs_q_p2_le_chat_relax": {
    title: "The Relaxed Cat",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -553, z: -264 },
    drops: ["N/A"],
    description: "A relaxed quest involving a calm cat companion.",
  },
  "fs_q_p2_le_clocher_de_la_sombre_messagere": {
    title: "The Dark Messenger's Bell Tower",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -585, z: -245 },
    drops: ["N/A"],
    description: "A quest centered around a haunted bell tower.",
  },
  "fs_q_p2_le_palier_2": {
    title: "Step 2",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -16, z: -823 },
    drops: ["N/A"],
    description: "A second step in an ongoing side quest series.",
  },
  "fs_q_p2_le_rituel_de_purification": {
    title: "The Purification Ritual",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -507, z: -60 },
    drops: ["N/A"],
    description: "A quest to complete a cleansing ritual.",
  },
  "fs_q_p2_le_toit_d_une_cabane": {
    title: "The Roof of a Cabin",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 639, z: -263 },
    drops: ["N/A"],
    description: "A quest involving the roof of a cabin shelter.",
  },
  "fs_q_p2_le_tribut_avant_le_verdict": {
    title: "The Tribute Before the Verdict",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -629, z: -296 },
    drops: ["N/A"],
    description: "A quest about offering tribute before judgment.",
  },
  "fs_q_p2_les_bases_d_une_cabane": {
    title: "The Cabin Base",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 639, z: -263 },
    drops: ["N/A"],
    description: "A quest focused on building a cabin foundation.",
  },
  "fs_q_p2_les_murs_d_une_cabane": {
    title: "The Cabin Walls",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 639, z: -263 },
    drops: ["N/A"],
    description: "A quest about putting up the walls of a cabin.",
  },
  "fs_q_p2_ma_premiere_arme": {
    title: "My First Weapon",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 16, z: -305 },
    drops: ["N/A"],
    description: "A quest where you obtain your first weapon.",
  },
  "fs_q_p2_nettoyer_les_cieux_de_taran": {
    title: "Cleaning Taran's Skies",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -432, z: 272 },
    drops: ["N/A"],
    description: "A quest to clear the skies above Taran.",
  },
  "fs_q_p2_non_c_est_de_la_sape": {
    title: "No, It's Fashion",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 696, z: -277 },
    drops: ["N/A"],
    description: "A quest about defending your choice of style.",
  },
  "fs_q_p2_parler_a_la_femme_etrange": {
    title: "Talk to the Strange Woman",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 13, z: -665 },
    drops: ["N/A"],
    description: "A quest to speak with an enigmatic woman.",
  },
  "fs_q_p2_retour_a_urbus": {
    title: "Return to Urbus",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: 62, z: -428 },
    drops: ["N/A"],
    description: "A quest to return back to the town of Urbus.",
  },
  "fs_q_p2_un_bon_petit_repas": {
    title: "A Good Little Meal",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -159, z: 10 },
    drops: ["N/A"],
    description: "A side quest centered around preparing a meal.",
  },
  "fs_q_p2_un_joueur_doit_faire_ses_preuves": {
    title: "A Player Must Prove Himself",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -436, z: -442 },
    drops: ["N/A"],
    description: "A quest in which the player must prove their worth.",
  },
  "fs_q_p2_un_peu_de_chaque": {
    title: "A Bit of Everything",
    type: "Quest",
    category: "sideQuests",
    floor: "floor2",
    coords: { x: -448, z: 267 },
    drops: ["N/A"],
    description: "A side quest that covers a bit of everything.",
  },
});

const RAW_MAP2_WAYPOINT_LINES = [
  "Alchemist - surface - -568 - -293",
  "Alchemist - surface - -574 - -299",
  "Lumberjack - surface - -575 - -293",
  "Accessories Blacksmith - surface - -618 - 529",
  "Accessories Blacksmith - underground - -694 - 205",
  "Accessories Blacksmith - surface - -818 - 98",
  "Accessories Blacksmith - surface - -498 - -746",
  "Accessories Blacksmith - surface - -38 - 199",
  "Accessories Blacksmith - surface - -713 - -109",
  "Accessories Blacksmith - surface - 78 - -71",
  "loot_buyer - surface - -581 - -273",
  "craft_accessories - surface - -502 - 334",
  "craft_accessories - underground - 339 - 505",
  "craft_accessories - surface - -194 - 20",
  "craft_ingots - surface - -777 - 17",
  "craft_accessories - surface - -602 - -285",
  "craft_accessories - surface - 111 - -408",
  "craft_weapons - underground - 591 - -700",
  "craft_weapons - underground - 727 - 265",
  "craft_armor - underground - 591 - -675",
  "craft_armor - underground - 722 - 264",
  "tool_merchant - underground - 722 - 268",
  "craft_ingots - surface - 868 - -295",
  "craft_ingots - surface - 124 - -385",
  "accessory_merchant - surface - -568 - -287",
  "occult_merchant - underground - -351 - 877",
  "occult_merchant - underground - -354 - 882",
  "occult_merchant - underground - -321 - 115",
  "equipment_merchant - surface - -576 - -288",
  "tool_merchant - surface - -583 - -286",
  "occult_merchant - underground - -343 - 879",
  "occult_merchant - underground - -345 - 887",
  "loot_buyer - surface - 129 - -380",
  "reforger - surface - 2 - -356",
  "loot_buyer - underground - 591 - -690",
  "loot_buyer - surface - -568 - -255",
  "loot_buyer - surface - 710 - -277",
  "loot_taker - underground - 728 - 268",
  "loot_taker - surface - 68 - -343",
  "Altar of the Two Moons - région - surface - 570 - -470",
  "Wavy Monster Bay - Biome - surface - -780 - 171",
  "Millennium Baobab - Biome - surface - -88 - -92",
  "Silver Fang Desert - Biome - surface - -372 - -556",
  "Emerald Wings Forest - Biome - surface - -550 - 476",
  "Sweet Forest - Biome - surface - 484 - -665",
  "Taran Cave - Biome - underground - -316 - -94",
  "Kaelor - Biome - surface - -583 - -264",
  "Lake of the Bulls - Biome - surface - 118 - -68",
  "Sablemor Veins - Biome - underground - 225 - 295",
  "Ngangas Houses - Biome - surface - -430 - -428",
  "Marome - Biome - surface - 721 - -281",
  "Blaze Nest - Biome - underground - -581 - 234",
  "Secret Oasis - Biome - surface - 798 - 253",
  "Melliona Hive - Biome - surface - 506 - -724",
  "Khesun Sanctuary - Biome - surface - -6 - 181",
  "Taran - Biome - surface - -427 - 272",
  "Necromancer's Tomb - Biome - underground - 721 - 244",
  "Taurus Tower - Biome - surface - -160 - 795",
  "Urbus - Biome - surface - 64 - -348",
  "Sanctuary Guardian - Boss Spawns - underground - 0 - 190",
  "Magnus - Boss Spawns - underground - 228 - 316",
  "Melisara - Boss Spawns - underground - 175 - -409",
  "Morveth - Boss Spawns - underground - 583 - -187",
  "Rugiboeuf - Boss Spawns - surface - -155 - 571",
  "Velindra - Boss Spawns - underground - 800 - 300",
  "Winnie - Boss Spawns - surface - 578 - -774",
  "Melliona's Hive Dungeon - Dungeons - surface - 506 - -724",
  "Necromancer's Tomb Dungeon - Dungeons - surface - 721 - 244",
  "kitchen_help - side_quest - surface - -563 - -255",
  "helping_yuko - side_quest - surface - -610 - -245",
  "it_stings_but_feels_good - side_quest - surface - -577 - -256",
  "hating_the_green - side_quest - surface - -431 - 279",
  "the_art_of_hides - side_quest - surface - 105 - -392",
  "the_art_of_feathers - side_quest - surface - 112 - -391",
  "the_imprint_of_the_seas - side_quest - surface - 620 - -567",
  "the_hunter_s_trial - side_quest - surface - -202 - -688",
  "the_onyx_of_knowledge - side_quest - surface - 724 - -301",
  "bushi_s_philosophy - side_quest - surface - -41 - 205",
  "the_relaxed_cat - side_quest - surface - -553 - -264",
  "the_dark_messenger_s_bell_tower - side_quest - surface - -585 - -245",
  "cabin_roof - side_quest - surface - 639 - -263",
  "cabin_foundation - side_quest - surface - 639 - -263",
  "cabin_walls - side_quest - surface - 639 - -263",
  "my_first_weapon - side_quest - surface - 16 - -305",
  "clearing_taran_s_skies - side_quest - surface - -432 - 272",
  "non_c_est_de_la_sape - side quest - surface - 696 - -277",
  "un_bon_petit_repas - side quest - surface - -159 - 10",
  "un_peu_de_chaque - side quest - surface - -448 - 267"
]

Object.assign(DATA, createMap2WaypointEntries(RAW_MAP2_WAYPOINT_LINES));

if (typeof MOB_AREA_MOBS === 'undefined') MOB_AREA_MOBS = {};
Object.assign(MOB_AREA_MOBS, {
  "silver-fang-desert-mobs": [
    { name: "Savanes Wolf" },
    { name: "Mountain Wolf" }
  ],
  "sweet-forest-mobs": [
    { name: "Forest Bear" }
  ],
  "wavy-monster-bay-mobs": [
    { name: "Lightning Harpy" },
    { name: "Dazzling Fish" }
  ],
  "emerald-wings-forest-mobs": [
    { name: "Earth Harpy" }
  ],
  "sanctuary-of-khesun-mobs": [
    { name: "Sanctuary Skeleton Shaman" },
    { name: "Sanctuary Skeleton Warrior" },
    { name: "Sanctuary Skeleton Archer" }
  ],
  "lake-of-bulls-mobs": [
    { name: "Monstrous Bull" },
    { name: "Taurus" }
  ],
  "melliona-hive-dungeon-mobs": [
    { name: "Dardroyal" },
    { name: "Worker" }
  ],
  "inferno-nest-mobs": [
    { name: "Fire Harpy" }
  ],
  "veins-of-sablemor-mobs": [
    { name: "Golem of Peter" }
  ],
  "sanctuary-of-khesun-interior-mobs": [
    { name: "Guardian Minion" }
  ],
  "forgotten-tomb-of-the-necromancer-mobs": [
    { name: "Fire Skeleton" },
    { name: "Fire Swordsman Skeleton" },
    { name: "Fire Lancer Skeleton" },
    { name: "Fire Archer Skeleton" },
    { name: "Fire Wizard Skeleton" },
    { name: "Fire Tank Skeleton" },
    { name: "Skeleton Soul" },
    { name: "Undead Brute" },
    { name: "Undead Gargoyle" }
  ]
});

// (Intentionally left unexposed to avoid altering globals)


MOB_AREAS.push(
  {
    id: "silver-fang-desert-mobs",
    title: "Silver Fang Desert",
    floor: "floor2",
    fill: "rgba(210, 180, 140, 0.26)",
    stroke: "#d2b48c",
    corners: [
      { x: -236, z: -638 },
      { x: -500, z: -588 },
      { x: -497, z: -473 },
      { x: -276, z: -540 }
    ]
  },
  {
    id: "sweet-forest-mobs",
    title: "Sweet Forest",
    floor: "floor2",
    fill: "rgba(162, 230, 120, 0.28)",
    stroke: "#8bcf46",
    corners: [
      { x: 363, z: -753 },
      { x: 327, z: -619 },
      { x: 596, z: -597 },
      { x: 572, z: -772 }
    ]
  },
  {
    id: "wavy-monster-bay-mobs",
    title: "Wavy Monster Bay",
    floor: "floor2",
    fill: "rgba(134, 126, 212, 0.28)",
    stroke: "#7f60dc",
    corners: [
      { x: -564, z: -52 },
      { x: -887, z: 133 },
      { x: -872, z: 232 },
      { x: -510, z: 135 }
    ]
  },
  {
    id: "emerald-wings-forest-mobs",
    title: "Emerald Wings Forest",
    floor: "floor2",
    fill: "rgba(144, 220, 126, 0.28)",
    stroke: "#68b941",
    corners: [
      { x: -629, z: 416 },
      { x: -615, z: 406 },
      { x: -585, z: 434 },
      { x: -531, z: 424 },
      { x: -534, z: 469 },
      { x: -555, z: 488 },
      { x: -588, z: 479 },
      { x: -586, z: 452 }
    ]
  },
  {
    id: "sanctuary-of-khesun-mobs",
    title: "Sanctuary of Khesun",
    floor: "floor2",
    fill: "rgba(250, 235, 123, 0.26)",
    stroke: "#e3d365",
    corners: [
      { x: -24, z: 130 },
      { x: 16, z: 127 },
      { x: 45, z: 213 },
      { x: -54, z: 244 },
      { x: -64, z: 202 }
    ]
  },
  {
    id: "lake-of-bulls-mobs",
    title: "Lake of the Bulls",
    floor: "floor2",
    fill: "rgba(170, 152, 204, 0.24)",
    stroke: "#9c8fb8",
    corners: [
      { x: 165, z: -150 },
      { x: 46, z: -126 },
      { x: 21, z: -64 },
      { x: 108, z: -16 },
      { x: 194, z: -51 }
    ]
  },
  {
    id: "melliona-hive-dungeon-mobs",
    title: "Melliona Hive Dungeon",
    floor: "floor2",
    underground: true,
    fill: "rgba(255, 184, 0, 0.24)",
    stroke: "#f4b400",
    corners: [
      { x: 557, z: -708 },
      { x: 652, z: -684 },
      { x: 652, z: -485 },
      { x: 515, z: -397 },
      { x: 230, z: -387 },
      { x: 230, z: -547 },
      { x: 343, z: -737 }
    ]
  },
  {
    id: "inferno-nest-mobs",
    title: "Inferno Nest",
    floor: "floor2",
    underground: true,
    fill: "rgba(255, 92, 0, 0.24)",
    stroke: "#ff5c00",
    corners: [
      { x: -768, z: 252 },
      { x: -543, z: 367 },
      { x: -448, z: 209 },
      { x: -570, z: 157 }
    ]
  },
  {
    id: "sanctuary-of-khesun-interior-mobs",
    title: "Interior of the Sanctuary of Khesun",
    floor: "floor2",
    underground: true,
    fill: "rgba(255, 248, 220, 0.28)",
    stroke: "#f2e8c6",
    corners: [
      { x: -42, z: 212 },
      { x: -42, z: 67 },
      { x: -21, z: 41 },
      { x: 6, z: 41 },
      { x: 28, z: 67 },
      { x: 28, z: 212 }
    ]
  },
  {
    id: "veins-of-sablemor-mobs",
    title: "The Veins of Sablemor",
    floor: "floor2",
    underground: true,
    fill: "rgba(245, 240, 90, 0.24)",
    stroke: "#d8d94b",
    corners: [
      { x: 152, z: 262 },
      { x: 152, z: 376 },
      { x: 289, z: 376 },
      { x: 287, z: 262 }
    ]
  },
  {
    id: "forgotten-tomb-of-the-necromancer-mobs",
    title: "Dungeon Forgotten Tomb of the Necromancer",
    floor: "floor2",
    underground: true,
    fill: "rgba(182, 74, 167, 0.24)",
    stroke: "#b24aa7",
    corners: [
      { x: 524, z: 289 },
      { x: 974, z: 289 },
      { x: 974, z: 39 },
      { x: 733, z: -150 },
      { x: 524, z: 144 }
    ]
  },
);

