// Floor-specific map data for floor3

Object.assign(DATA, {
  "furacas-guardian-of-the-labyrinth": {
    title: "Furacas, Guardian of the Labyrinth",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor3",
    coords: { x: 393, z: 340 },
    drops: ["N/A"],
    description: "Furacas, Guardian of the Labyrinth (Boss) — Coordinates X: 393 Z: 340",
  },
  "misty-wolf-alpha": {
    title: "Misty Wolf Alpha",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor3",
    coords: { x: 757, z: 790 },
    drops: ["N/A"],
    description: "Misty Wolf Alpha (Boss) — Coordinates X: 757 Z: 790",
  },
  "alpha-of-the-woods": {
    title: "Alpha of the Woods",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor3",
    coords: { x: 1060, z: 892 },
    drops: ["N/A"],
    description: "Alpha of the Woods (Boss) — Coordinates X: 1060 Z: 892",
  },
  "leader-of-the-bandits": {
    title: "Leader of the Bandits",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor3",
    coords: { x: 1175, z: 837 },
    drops: ["N/A"],
    description: "Leader of the Bandits (Boss) — Coordinates X: 1175 Z: 837",
  },
  "king-of-the-cave": {
    title: "King of the Cave",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor3",
    coords: { x: 886, z: 1098 },
    drops: ["N/A"],
    description: "King of the Cave (Boss) — Coordinates X: 886 Z: 1098",
  },
  "muffet-mother-of-black-spiders": {
    title: "Muffet, Mother of Black Spiders",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor3",
    coords: { x: 344, z: 1273 },
    drops: ["N/A"],
    description: "Muffet, Mother of Black Spiders (Boss) — Coordinates X: 344 Z: 1273",
  },
  "adoryll-the-bird-in-a-cage": {
    title: "Adoryll, the Bird in a Cage",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor3",
    coords: { x: 275, z: 1245 },
    drops: ["N/A"],
    description: "Adoryll, the Bird in a Cage (Boss) — Coordinates X: 275 Z: 1245",
  },
  "samurai-orc-boss": {
    title: "Samurai Orc Boss",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor3",
    coords: { x: 256, z: 1219 },
    drops: ["N/A"],
    description: "Samurai Orc Boss (Boss) — Coordinates X: 256 Z: 1219",
  },
  "labyrinth": {
    title: "Labyrinth",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 588, z: 195 },
    drops: ["N/A"],
    description: "Labyrinth (Biome) — Coordinates X: 588 Z: 195",
  },
  "entrance-to-the-labyrinth": {
    title: "Entrance to the Labyrinth",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 382, z: 433 },
    drops: ["N/A"],
    description: "Entrance to the Labyrinth (Biome) — Coordinates X: 382 Z: 433",
  },
  "dungeon-the-mysterious-islands": {
    title: "Dungeon The Mysterious Islands",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 860, z: 288 },
    drops: ["N/A"],
    description: "Dungeon The Mysterious Islands (Biome) — Coordinates X: 860 Z: 288",
  },
  "elessarh-mine": {
    title: "Elessarh Mine",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 928, z: 505 },
    drops: ["N/A"],
    description: "Elessarh Mine (Biome) — Coordinates X: 928 Z: 505",
  },
  "lysaat": {
    title: "Lysaat",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 346, z: 592 },
    drops: ["N/A"],
    description: "Lysaat (Biome) — Coordinates X: 346 Z: 592",
  },
  "weisslum": {
    title: "Weisslum",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 650, z: 607 },
    drops: ["N/A"],
    description: "Weisslum (Biome) — Coordinates X: 650 Z: 607",
  },
  "zumfut": {
    title: "Zumfut",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 932, z: 609 },
    drops: ["N/A"],
    description: "Zumfut (Biome) — Coordinates X: 932 Z: 609",
  },
  "aldarya": {
    title: "Aldarya",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 1083, z: 592 },
    drops: ["N/A"],
    description: "Aldarya (Biome) — Coordinates X: 1083 Z: 592",
  },
  "sylinga": {
    title: "Sylinga",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 163, z: 721 },
    drops: ["N/A"],
    description: "Sylinga (Biome) — Coordinates X: 163 Z: 721",
  },
  "ruins-of-avrylne": {
    title: "Ruins of Avrylne",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 543, z: 760 },
    drops: ["N/A"],
    description: "Ruins of Avrylne (Biome) — Coordinates X: 543 Z: 760",
  },
  "earan-forest": {
    title: "Earan Forest",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 477, z: 875 },
    drops: ["N/A"],
    description: "Earan Forest (Biome) — Coordinates X: 477 Z: 875",
  },
  "caverns": {
    title: "Caverns",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 528, z: 858 },
    drops: ["N/A"],
    description: "Caverns (Biome) — Coordinates X: 528 Z: 858",
  },
  "mist-refuge": {
    title: "Mist Refuge",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 705, z: 847 },
    drops: ["N/A"],
    description: "Mist Refuge (Biome) — Coordinates X: 705 Z: 847",
  },
  "mist-canyon": {
    title: "Mist Canyon",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 807, z: 855 },
    drops: ["N/A"],
    description: "Mist Canyon (Biome) — Coordinates X: 807 Z: 855",
  },
  "wolf-forest": {
    title: "Wolf Forest",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 970, z: 828 },
    drops: ["N/A"],
    description: "Wolf Forest (Biome) — Coordinates X: 970 Z: 828",
  },
  "ilmarin": {
    title: "Ilmarin",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 1049, z: 862 },
    drops: ["N/A"],
    description: "Ilmarin (Biome) — Coordinates X: 1049 Z: 862",
  },
  "black-market": {
    title: "Black Market",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 1121, z: 811 },
    drops: ["N/A"],
    description: "Black Market (Biome) — Coordinates X: 1121 Z: 811",
  },
  "bandit-camps": {
    title: "Bandit Camps",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 1138, z: 844 },
    drops: ["N/A"],
    description: "Bandit Camps (Biome) — Coordinates X: 1138 Z: 844",
  },
  "earan-land": {
    title: "Earan Land",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 587, z: 984 },
    drops: ["N/A"],
    description: "Earan Land (Biome) — Coordinates X: 587 Z: 984",
  },
  "terrialys-well": {
    title: "Terrialys Well",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 961, z: 1103 },
    drops: ["N/A"],
    description: "Terrialys Well (Biome) — Coordinates X: 961 Z: 1103",
  },
  "rest-of-ankyla": {
    title: "Rest of Ankyla",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 1105, z: 1043 },
    drops: ["N/A"],
    description: "Rest of Ankyla (Biome) — Coordinates X: 1105 Z: 1043",
  },
  "guild-base": {
    title: "Guild Base",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 775, z: 1200 },
    drops: ["N/A"],
    description: "Guild Base (Biome) — Coordinates X: 775 Z: 1200",
  },
  "adorylls-cage": {
    title: "Adoryll's cage",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 274, z: 1244 },
    drops: ["N/A"],
    description: "Adoryll's cage (Biome) — Coordinates X: 274 Z: 1244",
  },
  "orc-camps": {
    title: "Orc Camps",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 285, z: 1191 },
    drops: ["N/A"],
    description: "Orc Camps (Biome) — Coordinates X: 285 Z: 1191",
  },
  "triyag": {
    title: "Triyag",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 582, z: 1381 },
    drops: ["N/A"],
    description: "Triyag (Biome) — Coordinates X: 582 Z: 1381",
  },
  "swamp": {
    title: "Swamp",
    type: "Biome",
    category: "biomes",
    floor: "floor3",
    coords: { x: 633, z: 1258 },
    drops: ["N/A"],
    description: "Swamp (Biome) — Coordinates X: 633 Z: 1258",
  },
  "shishi-materials-for-shishi": {
    title: "Materials for ShiShi",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 589, z: 1362 },
    drops: ["N/A"],
    description: "Materials for ShiShi (Side Quest) — Coordinates X: 589 Z: 1362",
  },
  "caulette-the-man-who-lost-his-pants": {
    title: "The Man Who Lost His Pants",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 498, z: 600 },
    drops: ["N/A"],
    description: "The Man Who Lost His Pants (Side Quest) — Coordinates X: 498 Z: 600",
  },
  "mistress-herbalist-alicia-the-shadow-under-the-red-iris": {
    title: "The Shadow under the Red Iris",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 981, z: 544 },
    drops: ["N/A"],
    description: "The Shadow under the Red Iris (Side Quest) — Coordinates X: 981 Z: 544",
  },
  "meticulous-the-new-undermines": {
    title: "The new undermines",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 913, z: 673 },
    drops: ["N/A"],
    description: "The new undermines (Side Quest) — Coordinates X: 913 Z: 673",
  },
  "butterantivol-good-accounts-make-good-friends": {
    title: "Good accounts make good friends",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 526, z: 1409 },
    drops: ["N/A"],
    description: "Good accounts make good friends (Side Quest) — Coordinates X: 526 Z: 1409",
  },
  "elina-the-ashes-of-the-past": {
    title: "The Ashes of the Past",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 515, z: 859 },
    drops: ["N/A"],
    description: "The Ashes of the Past (Side Quest) — Coordinates X: 515 Z: 859",
  },
  "zik-the-prankster-goblins": {
    title: "The Prankster Goblins",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 870, z: 446 },
    drops: ["N/A"],
    description: "The Prankster Goblins (Side Quest) — Coordinates X: 870 Z: 446",
  },
  "lt53gaming-shadows-of-the-lost-forest": {
    title: "Shadows of the Lost Forest",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 510, z: 1080 },
    drops: ["N/A"],
    description: "Shadows of the Lost Forest (Side Quest) — Coordinates X: 510 Z: 1080",
  },
  "gromdar-blided-orcs-or-pulmed-orcs": {
    title: "Blided Orcs or Pulmed Orcs!",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 358, z: 591 },
    drops: ["N/A"],
    description: "Blided Orcs or Pulmed Orcs! (Side Quest) — Coordinates X: 358 Z: 591",
  },
  "alric-the-wild-threat": {
    title: "The wild threat",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 707, z: 854 },
    drops: ["N/A"],
    description: "The wild threat (Side Quest) — Coordinates X: 707 Z: 854",
  },
  "elara-the-great-feast": {
    title: "The Great Feast",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 874, z: 716 },
    drops: ["N/A"],
    description: "The Great Feast (Side Quest) — Coordinates X: 874 Z: 716",
  },
  "narancia-the-mask-of-the-memory-tree": {
    title: "The mask of the Memory Tree",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 201, z: 714 },
    drops: ["N/A"],
    description: "The mask of the Memory Tree (Side Quest) — Coordinates X: 201 Z: 714",
  },
  "lirael-orc-roll": {
    title: "Orc & Roll",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 140, z: 736 },
    drops: ["N/A"],
    description: "Orc & Roll (Side Quest) — Coordinates X: 140 Z: 736",
  },
  "regula-regulation-quota": {
    title: "Regulation quota",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 162, z: 771 },
    drops: ["N/A"],
    description: "Regulation quota (Side Quest) — Coordinates X: 162 Z: 771",
  },
  "shingetsou-a-very-strange-lumberjack": {
    title: "A very strange lumberjack",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 628, z: 1440 },
    drops: ["N/A"],
    description: "A very strange lumberjack (Side Quest) — Coordinates X: 628 Z: 1440",
  },
  "sanji-2-paths-1-choice": {
    title: "2 Paths, 1 Choice",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 427, z: 774 },
    drops: ["N/A"],
    description: "2 Paths, 1 Choice (Side Quest) — Coordinates X: 427 Z: 774",
  },
  "sylva-the-dance-of-the-sleeping-treants": {
    title: "The Dance of the Sleeping Treants",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 583, z: 1428 },
    drops: ["N/A"],
    description: "The Dance of the Sleeping Treants (Side Quest) — Coordinates X: 583 Z: 1428",
  },
  "sanraol-the-forge-of-a-god": {
    title: "The Forge of a God",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 608, z: 1046 },
    drops: ["N/A"],
    description: "The Forge of a God (Side Quest) — Coordinates X: 608 Z: 1046",
  },
  "zilda-the-legend-of-zilda": {
    title: "The legend of Zilda",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 1068, z: 919 },
    drops: ["N/A"],
    description: "The legend of Zilda (Side Quest) — Coordinates X: 1068 Z: 919",
  },
  "accoow-the-ascalon-oath": {
    title: "The Ascalon Oath",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 133, z: 995 },
    drops: ["N/A"],
    description: "The Ascalon Oath (Side Quest) — Coordinates X: 133 Z: 995",
  },
  "guy-article-proposal": {
    title: "Article proposal",
    type: "Quest",
    category: "sideQuests",
    floor: "floor3",
    coords: { x: 876, z: 555 },
    drops: ["N/A"],
    description: "Article proposal (Side Quest) — Coordinates X: 876 Z: 555",
  },
  "ancient-wood-armor-blacksmith": {
    title: "Ancient Wood Armor Blacksmith",
    type: "NPC",
    category: "armorBlacksmith",
    floor: "floor3",
    coords: { x: 780, z: 253 },
    drops: ["N/A"],
    description: "Ancient Wood Armor Blacksmith",
  },
  "amethyst-armor-blacksmith": {
    title: "Amethyst Armor Blacksmith",
    type: "NPC",
    category: "armorBlacksmith",
    floor: "floor3",
    coords: { x: 627, z: 1370 },
    drops: ["N/A"],
    description: "Amethyst Armor Blacksmith",
  },
  "former-blacksmith": {
    title: "Former Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 176, z: 716 },
    drops: ["N/A"],
    description: "Former Blacksmith",
  },
  "adventurers-shoemaker": {
    title: "Adventurer's Shoemaker",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 358, z: 572 },
    drops: ["N/A"],
    description: "Adventurer's Shoemaker",
  },
  "sylnovar-accessories-blacksmith": {
    title: "Sylnovar Accessories Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 918, z: 579 },
    drops: ["N/A"],
    description: "Sylnovar Accessories Blacksmith",
  },
  "bandit-loot-reseller": {
    title: "Bandit Loot Reseller",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 1211, z: 751 },
    underground: true,
    drops: ["N/A"],
    description: "Bandit Loot Reseller",
  },
  "accessories-bandit-blacksmith": {
    title: "Accessories Bandit Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 1192, z: 741 },
    underground: true,
    drops: ["N/A"],
    description: "Accessories Bandit Blacksmith",
  },
  "low-corruption-bracelet-blacksmith": {
    title: "Low Corruption Bracelet Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 439, z: 474 },
    underground: true,
    drops: ["N/A"],
    description: "Low Corruption Bracelet Blacksmith",
  },
  "tribe-belt-blacksmith": {
    title: "Tribe Belt Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 235, z: 1200 },
    drops: ["N/A"],
    description: "Tribe Belt Blacksmith",
  },
  "leatherworker": {
    title: "Leatherworker",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 624, z: 1380 },
    drops: ["N/A"],
    description: "Leatherworker",
  },
  "ring-blacksmith": {
    title: "Ring Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 562, z: 1409 },
    drops: ["N/A"],
    description: "Ring Blacksmith",
  },
  "glove-blacksmith": {
    title: "Glove Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 567, z: 1411 },
    drops: ["N/A"],
    description: "Glove Blacksmith",
  },
  "amulet-blacksmith": {
    title: "Amulet Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 559, z: 1367 },
    drops: ["N/A"],
    description: "Amulet Blacksmith",
  },
  "bracelet-blacksmith": {
    title: "Bracelet Blacksmith",
    type: "NPC",
    category: "accessoriesBlacksmith",
    floor: "floor3",
    coords: { x: 561, z: 1361 },
    drops: ["N/A"],
    description: "Bracelet Blacksmith",
  },
  "assistant-alchimiste": {
    title: "Assistant to the Alchemist",
    type: "NPC",
    category: "alchemist",
    floor: "floor3",
    coords: { x: 826, z: 653 },
    drops: ["N/A"],
    description: "Assistant to the Alchemist",
  },
  "alchemist": {
    title: "Alchemist",
    type: "NPC",
    category: "alchemist",
    floor: "floor3",
    coords: { x: 830, z: 657 },
    drops: ["N/A"],
    description: "Alchemist",
  },
  "cabinetmaker": {
    title: "Cabinetmaker",
    type: "NPC",
    category: "lumberjack",
    floor: "floor3",
    coords: { x: 152, z: 731 },
    drops: ["N/A"],
    description: "Cabinetmaker",
  },
  "complex-rune-craftsman": {
    title: "Complex Rune Craftsman",
    type: "NPC",
    category: "runeCraftsmen",
    floor: "floor3",
    coords: { x: 853, z: 527 },
    drops: ["N/A"],
    description: "Complex Rune Craftsman",
  },
  "basic-rune-craftsman": {
    title: "Basic Rune Craftsman",
    type: "NPC",
    category: "runeCraftsmen",
    floor: "floor3",
    coords: { x: 912, z: 592 },
    drops: ["N/A"],
    description: "Basic Rune Craftsman",
  },
  "occult-runes-merchant": {
    title: "Occult Runes Merchant",
    type: "NPC",
    category: "runeCraftsmen",
    floor: "floor3",
    coords: { x: 723, z: 151 },
    drops: ["N/A"],
    description: "Occult Runes Merchant",
  },
  "refaire-refaiter": {
    title: "Refaiter",
    type: "NPC",
    category: "refaire",
    floor: "floor3",
    coords: { x: 345, z: 583 },
    drops: ["N/A"],
    description: "Transforms Resources and Spider Threads to make useful strings in making Accessories.",
  },
  "local-lumberjack": {
    title: "Local lumberjack",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 159, z: 716 },
    drops: ["N/A"],
    description: "Local lumberjack - Buys Loot.",
  },
  "spider-loot-repreneur": {
    title: "Spider Loot Repreneur",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 532, z: 860 },
    drops: ["N/A"],
    description: "Spider Loot Repreneur - Buys Loot.",
  },
  "orc-loot-repreneur": {
    title: "Orc Loot Repreneur",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 309, z: 1055 },
    drops: ["N/A"],
    description: "Orc Loot Repreneur - Buys Loot.",
  },
  "local-farmer": {
    title: "Local Farmer",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 601, z: 1032 },
    drops: ["N/A"],
    description: "Local Farmer - Buys Loot.",
  },
  "goblin-loot-repreneur": {
    title: "Goblin Loot Repreneur",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 938, z: 1065 },
    drops: ["N/A"],
    description: "Goblin Loot Repreneur - Buys Loot.",
  },
  "loot-buyer-sylvaer": {
    title: "Loot Buyer Sylvaer",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 609, z: 1373 },
    drops: ["N/A"],
    description: "Loot Buyer Sylvaer - Buys Loot.",
  },
  "loot-buyer-treant": {
    title: "Loot Buyer Treant",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 499, z: 1390 },
    drops: ["N/A"],
    description: "Loot Buyer Treant - Buys Loot.",
  },
  "loot-buyer-sylnovar": {
    title: "Loot Buyer Sylnovar",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 824, z: 652 },
    drops: ["N/A"],
    description: "Loot Buyer Sylnovar - Buys Loot.",
  },
  "miner-of-the-corner": {
    title: "Miner of the Corner",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 891, z: 474 },
    underground: true,
    drops: ["N/A"],
    description: "Miner of the Corner - Buys Loot.",
  },
  "bandit-loot-repreneur": {
    title: "Bandit Loot Repreneur",
    type: "NPC",
    category: "lootBuyers",
    floor: "floor3",
    coords: { x: 1185, z: 732 },
    underground: true,
    drops: ["N/A"],
    description: "Bandit Loot Repreneur - Buys Loot.",
  },
  "equipment-merchant-921-588": {
    title: "Equipment Merchant",
    type: "NPC",
    category: "equipmentMerchants",
    floor: "floor3",
    coords: { x: 921, z: 588 },
    drops: ["N/A"],
    description: "Equipment Merchant",
  },
  "equipment-merchant-544-1320": {
    title: "Equipment Merchant",
    type: "NPC",
    category: "equipmentMerchants",
    floor: "floor3",
    coords: { x: 544, z: 1320 },
    drops: ["N/A"],
    description: "Equipment Merchant",
  },
  "consumables-merchant-918-605": {
    title: "Consumables Merchant",
    type: "NPC",
    category: "consumablesMerchants",
    floor: "floor3",
    coords: { x: 918, z: 605 },
    drops: ["N/A"],
    description: "Consumables Merchant",
  },
  "consumables-merchant-568-1320": {
    title: "Consumables Merchant",
    type: "NPC",
    category: "consumablesMerchants",
    floor: "floor3",
    coords: { x: 568, z: 1320 },
    drops: ["N/A"],
    description: "Consumables Merchant",
  },
  "reinforced-tools-merchant": {
    title: "Reinforced Tools Merchant",
    type: "NPC",
    category: "toolMerchants",
    floor: "floor3",
    coords: { x: 938, z: 586 },
    drops: ["N/A"],
    description: "Reinforced Tools Merchant",
  },
  "glove-merchant": {
    title: "Glove Merchant",
    type: "NPC",
    category: "accessoriesMerchants",
    floor: "floor3",
    coords: { x: 505, z: 1408 },
    drops: ["N/A"],
    description: "Glove Merchant",
  },
  "ringman": {
    title: "Ringman",
    type: "NPC",
    category: "accessoriesMerchants",
    floor: "floor3",
    coords: { x: 537, z: 1382 },
    drops: ["N/A"],
    description: "Ringman",
  },
  "simple-accessories-merchant": {
    title: "Simple Accessories Merchant",
    type: "NPC",
    category: "accessoriesMerchants",
    floor: "floor3",
    coords: { x: 570, z: 1378 },
    drops: ["N/A"],
    description: "Simple Accessories Merchant",
  },
  "bracelet-merchant": {
    title: "Bracelet Merchant",
    type: "NPC",
    category: "accessoriesMerchants",
    floor: "floor3",
    coords: { x: 537, z: 1352 },
    drops: ["N/A"],
    description: "Bracelet Merchant",
  },
  "artifact-merchant": {
    title: "Artifact Merchant",
    type: "NPC",
    category: "accessoriesMerchants",
    floor: "floor3",
    coords: { x: 561, z: 1338 },
    drops: ["N/A"],
    description: "Artifact Merchant",
  },
  "amulet-merchant": {
    title: "Amulet Merchant",
    type: "NPC",
    category: "accessoriesMerchants",
    floor: "floor3",
    coords: { x: 581, z: 1338 },
    drops: ["N/A"],
    description: "Amulet Merchant",
  },
  "occult-gloves-merchant": {
    title: "Occult Gloves Merchant",
    type: "NPC",
    category: "occultMerchants",
    floor: "floor3",
    coords: { x: 344, z: 1298 },
    drops: ["N/A"],
    description: "Occult Merchant",
  },
  "occult-rings-merchant": {
    title: "Occult Rings Merchant",
    type: "NPC",
    category: "occultMerchants",
    floor: "floor3",
    coords: { x: 985, z: 1017 },
    underground: true,
    drops: ["N/A"],
    description: "Occult Merchant",
  },
  "occult-artifact-merchant": {
    title: "Occult Artifact Merchant",
    type: "NPC",
    category: "occultMerchants",
    floor: "floor3",
    coords: { x: 939, z: 510 },
    underground: true,
    drops: ["N/A"],
    description: "Occult Merchant",
  },
});

MOB_AREAS.push(
);
