const CALIBRATION_MAP_SIZE = 900;

const MAP_CALIBRATION = {
  floor1: {
    centerPixel: { x: 450, y: 450 },
    centerGame: { x: 2545.6, z: 2550 },
    radiusPixel: 450,
    radiusGame: 2498.1
  },
  floor2: {
    centerPixel: { x: 450, y: 450 },
    centerGame: { x: -1.3, z: 0.8 },
    radiusPixel: 450,
    radiusGame: 1072.5
  },
  floor3: {
    centerPixel: { x: 450, y: 450 },
    centerGame: { x: 597, z: 771 },
    radiusPixel: 450,
    radiusGame: 850
  }
};

function getReferenceSize(dimensions) {
  if (!dimensions) return CALIBRATION_MAP_SIZE;
  const w = Number(dimensions.width);
  const h = Number(dimensions.height);
  if (!Number.isFinite(w) || !Number.isFinite(h) || w <= 0 || h <= 0) {
    return CALIBRATION_MAP_SIZE;
  }
  return Math.min(w, h);
}

function rawToCalibrationPixels(rawX, rawY, dimensions) {
  const referenceSize = getReferenceSize(dimensions);
  const ratio = CALIBRATION_MAP_SIZE / referenceSize;
  return {
    x: rawX * ratio,
    y: rawY * ratio
  };
}

function calibrationPixelsToRaw(px, py, dimensions) {
  const referenceSize = getReferenceSize(dimensions);
  const ratio = referenceSize / CALIBRATION_MAP_SIZE;
  return {
    rawX: px * ratio,
    rawY: py * ratio
  };
}

function mapWebsiteCoordinates(rawX, rawY, floor, dimensions) {
  const calibration = MAP_CALIBRATION[floor];
  if (!calibration) return null;

  const pixel = rawToCalibrationPixels(rawX, rawY, dimensions);
  const scale = calibration.radiusGame / calibration.radiusPixel;

  return {
    x: calibration.centerGame.x + (pixel.x - calibration.centerPixel.x) * scale,
    z: calibration.centerGame.z + (pixel.y - calibration.centerPixel.y) * scale
  };
}

function invertMapCoordinates(x, z, floor, dimensions) {
  const calibration = MAP_CALIBRATION[floor];
  if (!calibration) return null;

  const scale = calibration.radiusPixel / calibration.radiusGame;
  const pixelX = calibration.centerPixel.x + (x - calibration.centerGame.x) * scale;
  const pixelY = calibration.centerPixel.y + (z - calibration.centerGame.z) * scale;

  return calibrationPixelsToRaw(pixelX, pixelY, dimensions);
}

const DATA = {
  "swamp-putride": {
    title: "Swamp Putride",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1343, z: 3051 },
    drops: ["N/A"],
    description: "A dense and hostile marsh, where mist poisons the air and masks dangers. Few emerge unscathed...",
  },
  "vallhat": {
    title: "Vallhat",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 448, z: 3038 },
    drops: ["N/A"],
    description: "Perched at the top of a windy massif, Vallhat watches, silent and isolated. Its heights hide many secrets.",
  },
  "cyclorim": {
    title: "Cyclorim",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1165, z: 3540 },
    drops: ["N/A"],
    description: "An ancient arena carved from red rock. It is said that a single eye still watches over it, ready to judge intruders by brute force.",
  },
  "hanaka": {
    title: "Hanaka",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1484, z: 3425 },
    drops: ["N/A"],
    description: "A wooded hamlet nestled between the hills where wild boars prowl on the edge. Cradle of the first clashes.",
  },
  "town-of-beginnings": {
    title: "Town of Beginnings",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1800, z: 4282 },
    drops: ["N/A"],
    description: "The Town of Beginnings is a peaceful haven in a still unknown virtual world. This is where every adventure begins.",
  },
  "petals-valley": {
    title: "Petals Valley",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1007, z: 4159 },
    drops: ["N/A"],
    description: "An enchanted valley where the petals dance in the wind. The scent of flowers soothes the souls of travelers. But behind the beauty... lies an ancient secret.",
  },
  "valley-of-wolfs": {
    title: "Valley of Wolfs",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 2553, z: 3848 },
    drops: ["N/A"],
    description: "A foggy valley where the howls still resonate. It is said that no wolf hunts there alone... Their shadows watch from the heights.",
  },
  "abandoned-castle": {
    title: "Abandoned Castle",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 2839, z: 4682 },
    drops: ["N/A"],
    description: "The ruins of a forgotten castle, eaten away by time. Its collapsed walls still whisper the echoes of yesteryear. A place that even the light seems to flee.",
  },
  "ika-archipelago": {
    title: "Ika Archipelago",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 3299, z: 4084 },
    drops: ["N/A"],
    description: "A tropical archipelago where giant tortoises gather. Each island hides ancient mysteries and unique wildlife. Calm is just a facade...",
  },
  "mizunari": {
    title: "Mizunari",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 3139, z: 3673 },
    drops: ["N/A"],
    description: "Small peaceful village nestled on the edge of a clear lake. The inhabitants live to the rhythm of the waves and the wind. A perfect place to breathe between two battles.",
  },
  "geldorak-mine": {
    title: "Geldorak Mine",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 4171, z: 3879 },
    drops: ["N/A"],
    description: "Dug into the heart of the mountain, the Geldorak mine was once home to a colony of renowned miners. But one day a scream rang out in the galleries... Since then, the corridors have been sealed and no one dares to go down there anymore.",
  },
  "og-district": {
    title: "OG District",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 2308, z: 3252 },
    drops: ["N/A"],
    description: "The stronghold of the renowned and feared OG Guild. A strategic location reserved for elite veterans. The walls exude glory and past victories.",
  },
  "castlemist": {
    title: "Castlemist",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 2870, z: 2975 },
    drops: ["N/A"],
    description: "Perched at the top of a forgotten ridge, the hamlet of CastelBrume watches over the valley. Its mills howl in the icy mist, like a call to lost souls...",
  },
  "water-lily-lake": {
    title: "Water Lily Lake",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 2601, z: 2759},
    drops: ["N/A"],
    description: "Calm and mystery surround its troubled waters... A place of meditation, but also of disappearance.",
  },
  "garden-of-giants": {
    title: "Garden of Giants",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 367, z: 2422 },
    drops: ["N/A"],
    description: "A forgotten place where nature has reclaimed its rights. Some say they hear voices whispered in the wind, as if the giants were still watching. A peaceful oasis... in appearance only.",
  },
  "arakh-nol": {
    title: "Arakh'Nol",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1218, z: 1394 },
    drops: ["N/A"],
    description: "In the depths of Arakh'Nol, light struggles to break through. Each tree is knotted with thick, living webs. The whispers of the wind hide the whispers of ancient spirits, and those who stray from them rarely guess the stories being told. A forgotten entity weaves more than traps there.",
  },
  "virelune": {
    title: "Virelune",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1570, z: 1966 },
    drops: ["N/A"],
    description: "Nestled on the edge of an unfathomable sea chasm, the village of Virelune lives to the rhythm of lunar tides. Fishermen say they see two moons reflected in the waters... But one of them never follows the sky.",
  },
  "crystal-peak-mine": {
    title: "Crystal Peak Mine",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 2444, z: 1717 },
    drops: ["N/A"],
    description: "This old mine contains crystals of exceptional purity. It is said that their brilliance is linked to human emotions... But some miners, fascinated, got lost there forever.",
  },
  "tolbana-crystal": {
    title: "Tolbana Crystal",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 3044, z: 1181 },
    drops: ["N/A"],
    description: "Luminescent crystals with mysterious properties. Protected by Tolbana mages...",
  },
  "kobold-tower": {
    title: "Kobold Tower",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 3407, z: 960 },
    drops: ["N/A"],
    description: "An ancient ruined tower, lair of Ilfang Lord Kobold. Dark murmurs rise from its depths.",
  },
  "tolbana": {
    title: "Tolbana",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 3310, z: 1608 },
    drops: ["N/A"],
    description: "Built on the mountainside, Tolbana is home to the largest magical libraries in the known world. Its streets vibrate with energy, and its towers resonate with the echo of age-old incantations.",
  },
  "snow-citadel": {
    title: "Snow Citadel",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 3992, z: 1998 },
    drops: ["N/A"],
    description: "Once an impregnable bastion, the Snow Citadel was the scene of a forgotten siege, lost in the snowflakes of time. Its ramparts, frozen in ice, guard the scars. Today, only the most daring dare to pass through its doors...",
  },
  "merchant-guild": {
    title: "Merchant Guild",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 4770, z: 2410 },
    drops: ["N/A"],
    description: "The Merchants Guild Headquarters, a lively place where riches and secrets are exchanged. The streets are teeming with activity and negotiation.",
  },
  "candelia": {
    title: "Candelia",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1999, z: 753 },
    drops: ["N/A"],
    description: "Nestled between the steep peaks, Candelia seems frozen in time. Its lanterns flicker without wind, and the fields never wither. The ancients say that souls still whisper there at nightfall...",
  },
  "lair-of-aepep": {
    title: "Lair of Aepep",
    type: "Biome",
    category: "biomes",
    floor: "floor1",
    coords: { x: 1387, z: 2029 },
    drops: ["N/A"],
    description: "In the heart of a forgotten cave sleeps an ancient serpent: Aepep No one knows if he's awake... or still dreaming. Its gigantic body would have shaped the galleries.",
    underground: true
  },
  "xal-zirith-dungeon": {
    title: "Xal'zirith Dungeon",
    type: "Dungeon",
    category: "dungeons",
    floor: "floor1",
    coords: { x: 1032, z: 1172 },
    drops: ["N/A"],
    description: "A fractured ruin wrapped in red mist where sword skills desync in narrow halls. Parties that clear its upper chambers often hear one extra set of footsteps behind them.",
  },
  "kobold-tower-dungeon": {
    title: "Kobold Tower",
    type: "Dungeon",
    category: "dungeons",
    floor: "floor1",
    coords: { x: 3407, z: 960 },
    drops: ["N/A"],
    description: "The old boss tower from early Aincrad records, layered with trap stairs and ambush rooms. Every floor feels like a raid rehearsal built to punish hesitation.",
  },
  "fallen-labyrinth-dungeon": {
    title: "Fallen Labyrinth Dungeon",
    type: "Dungeon",
    category: "dungeons",
    floor: "floor1",
    coords: { x: 2381, z: 2403 },
    drops: ["N/A"],
    description: "A maze that rewrites its routes after each elite pull, like the system is learning your pathing. Scouts call it the place where map memory goes to die.",
  },
  "nasgul-sub-dungeon": {
    title: "Nasgul Sub-Dungeon",
    type: "Dungeon",
    category: "dungeons",
    floor: "floor1",
    coords: { x: 2780, z: 4410 },
    drops: ["N/A"],
    description: "Hidden beneath broken stone circles, this sub-dungeon is tuned for tight duels and poison attrition. The deeper vaults feel like a side route meant for front-liners only.",
  },
  "geldorak-mine-dungeon": {
    title: "Geldorak Mine Dungeon",
    type: "Dungeon",
    category: "dungeons",
    floor: "floor1",
    coords: { x: 4268, z: 3876 },
    drops: ["N/A"],
    description: "Collapsed ore tunnels now host armored mobs that patrol like a disciplined guild squad. Miners left warning runes at each fork, but most parties still pick the wrong descent.",
  },
  "sq-ayaka": {
    title: "Ayaka",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 479, z: 3014 },
    drops: ["N/A"],
    description: "Side Quest NPC in Vallhat.",
  },
  "sq-bartok": {
    title: "Bartok",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1526, z: 3375 },
    drops: ["N/A"],
    description: "Side Quest NPC in Hanaka.",
  },
  "sq-bunta": {
    title: "Bunta",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1533, z: 4329 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-corentin": {
    title: "Corentin",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3291, z: 2908 },
    drops: ["N/A"],
    description: "Side Quest NPC in Castlemist.",
  },
  "sq-daiki": {
    title: "Daiki",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 405, z: 3077 },
    drops: ["N/A"],
    description: "Side Quest NPC in Vallhat.",
  },
  "sq-elwyn": {
    title: "Elwyn",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3113, z: 3702 },
    drops: ["N/A"],
    description: "Side Quest NPC in Mizunari.",
  },
  "sq-emilie": {
    title: "Emilie",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1984, z: 754 },
    drops: ["N/A"],
    description: "Side Quest NPC in Candelia.",
  },
  "sq-fira": {
    title: "Fira",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3395, z: 2948 },
    drops: ["N/A"],
    description: "Side Quest NPC in Castlemist.",
  },
  "sq-genzo": {
    title: "Genzo",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1532, z: 3374 },
    drops: ["N/A"],
    description: "Side Quest NPC in Hanaka.",
  },
  "sq-gilbert": {
    title: "Gilbert",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1700, z: 1018 },
    drops: ["N/A"],
    description: "Side Quest NPC in Candelia.",
  },
  "sq-gilmar": {
    title: "Gilmar",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1958, z: 793 },
    drops: ["N/A"],
    description: "Side Quest NPC in Candelia.",
  },
  "sq-greta": {
    title: "Greta",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1438, z: 3407 },
    drops: ["N/A"],
    description: "Side Quest NPC in Hanaka.",
  },
  "sq-haruto": {
    title: "Haruto",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1866, z: 2112 },
    drops: ["N/A"],
    description: "Side Quest NPC in Virelune.",
  },
  "sq-horace": {
    title: "Horace",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3084, z: 1914 },
    drops: ["N/A"],
    description: "Side Quest NPC in Tolbana.",
  },
  "sq-inari": {
    title: "Inari",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1758, z: 4735 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-john": {
    title: "John",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3224, z: 2891 },
    drops: ["N/A"],
    description: "Side Quest NPC in Castlemist.",
  },
  "sq-juliet": {
    title: "Juliet",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1638, z: 2048 },
    drops: ["N/A"],
    description: "Side Quest NPC in Virelune.",
  },
  "sq-lila": {
    title: "Lila",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 2033, z: 3858 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-louise": {
    title: "Louise",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3148, z: 3704 },
    drops: ["N/A"],
    description: "Side Quest NPC in Mizunari.",
  },
  "sq-luke": {
    title: "Luke",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1624, z: 1851 },
    drops: ["N/A"],
    description: "Side Quest NPC in Virelune.",
  },
  "sq-martine": {
    title: "Martine",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3151, z: 3671 },
    drops: ["N/A"],
    description: "Side Quest NPC in Mizunari.",
  },
  "sq-maya": {
    title: "Maya",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1501, z: 3561 },
    drops: ["N/A"],
    description: "Side Quest NPC in Hanaka.",
  },
  "sq-meiko": {
    title: "Meiko",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1271, z: 4310 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-michelle": {
    title: "Michelle",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3131, z: 3667 },
    drops: ["N/A"],
    description: "Side Quest NPC in Mizunari.",
  },
  "sq-milla": {
    title: "Milla",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 2206, z: 4187 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-monica": {
    title: "Monica",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1573, z: 1952 },
    drops: ["N/A"],
    description: "Side Quest NPC in Virelune.",
  },
  "sq-orin": {
    title: "Orin",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1745, z: 4726 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-headlights": {
    title: "Headlights",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 3149, z: 3712 },
    drops: ["N/A"],
    description: "Side Quest NPC in Mizunari.",
  },
  "sq-peter": {
    title: "Peter",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 2018, z: 877 },
    drops: ["N/A"],
    description: "Side Quest NPC in Candelia.",
  },
  "sq-rikyu": {
    title: "Rikyu",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1556, z: 4315 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-rina": {
    title: "Rina",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1501, z: 3534 },
    drops: ["N/A"],
    description: "Side Quest NPC in Hanaka.",
  },
  "sq-romeo": {
    title: "Romeo",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1991, z: 832 },
    drops: ["N/A"],
    description: "Side Quest NPC in Candelia.",
  },
  "sq-sam": {
    title: "Sam",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1600, z: 2006 },
    drops: ["N/A"],
    description: "Side Quest NPC in Virelune.",
  },
  "sq-saria": {
    title: "Saria",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1272, z: 4318 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-saya": {
    title: "Saya",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 491, z: 3028 },
    drops: ["N/A"],
    description: "Side Quest NPC in Vallhat.",
  },
  "sq-sister-thera": {
    title: "Sister Thera",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1405, z: 3435 },
    drops: ["N/A"],
    description: "Side Quest NPC in Hanaka.",
  },
  "sq-tilda": {
    title: "Tilda",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1884, z: 4009 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-toban": {
    title: "Toban",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1356, z: 3441 },
    drops: ["N/A"],
    description: "Side Quest NPC in Hanaka.",
  },
  "sq-tomoko": {
    title: "Tomoko",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 1956, z: 815 },
    drops: ["N/A"],
    description: "Side Quest NPC in Candelia.",
  },
  "sq-varn": {
    title: "Varn",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 2068, z: 4291 },
    drops: ["N/A"],
    description: "Side Quest NPC in Town of Beginnings.",
  },
  "sq-yannis": {
    title: "Yannis",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 2014, z: 834 },
    drops: ["N/A"],
    description: "Side Quest NPC in Candelia.",
  },
  "sq-ceyla": {
    title: "Ceyla",
    type: "Quest",
    category: "sideQuests",
    floor: "floor1",
    coords: { x: 499, z: 3050 },
    drops: ["N/A"],
    description: "Side Quest NPC in Vallhat.",
  },
  "journeyman-alchemist-tolbana": {
    title: "Alchemist",
    type: "NPC",
    category: "alchemist",
    floor: "floor1",
    coords: { x: 3336, z: 1597 },
    drops: ["N/A"],
    description: "Alchemist - X: 3336 Z: 1597",
  },
  "journeyman-alchemist-town": {
    title: "Alchemist",
    type: "NPC",
    category: "alchemist",
    floor: "floor1",
    coords: { x: 1773, z: 4085 },
    drops: ["N/A"],
    description: "Alchemist, Crystallograph, Assistant to the Alchemist - X: 1773 Z: 4085",
  },
  "journeyman-lumberjack": {
    title: "Lumberjack",
    type: "NPC",
    category: "lumberjack",
    floor: "floor1",
    coords: { x: 2462, z: 4287 },
    drops: ["N/A"],
    description: "Lumberjack - X: 2462 Z: 4287",
  },
  "pumba-1": {
    title: "Corrupted Pumba",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1857, z: 3594 },
    drops: ["N/A"],
    description: "A wild beast from the forests of the first level. He charges relentlessly, driven by primitive rage.",
  },
  "pumba-2": {
    title: "Corrupted Pumba",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1675, z: 3569 },
    drops: ["N/A"],
    description: "A wild beast from the forests of the first level. He charges relentlessly, driven by primitive rage.",
  },
  "pumba-3": {
    title: "Corrupted Pumba",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1972, z: 3571 },
    drops: ["N/A"],
    description: "A wild beast from the forests of the first level. He charges relentlessly, driven by primitive rage.",
  },
  "pumba-4": {
    title: "Corrupted Pumba",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1929, z: 3503 },
    drops: ["N/A"],
    description: "A wild beast from the forests of the first level. He charges relentlessly, driven by primitive rage.",
  },
  "colossal-guardian-1": {
    title: "Colossal Guardian",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1236, z: 2960 },
    drops: ["N/A"],
    description: "Forged in stone and awakened by ancient magic, it guards forgotten lands against any intrusion. His steps alone make the forest shake...",
  },
  "colossal-guardian-2": {
    title: "Colossal Guardian",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1272, z: 3138 },
    drops: ["N/A"],
    description: "Forged in stone and awakened by ancient magic, it guards forgotten lands against any intrusion. His steps alone make the forest shake...",
  },
  "colossal-guardian-3": {
    title: "Colossal Guardian",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1075, z: 3240 },
    drops: ["N/A"],
    description: "Forged in stone and awakened by ancient magic, it guards forgotten lands against any intrusion. His steps alone make the forest shake...",
  },
  "colossal-guardian-4": {
    title: "Colossal Guardian",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 4575, z: 1600 },
    drops: ["N/A"],
    description: "Forged in stone and awakened by ancient magic, it guards forgotten lands against any intrusion. His steps alone make the forest shake...",
  },
  "gorbel": {
    title: "Gorbel",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 300, z: 3190 },
    drops: ["N/A"],
    description: "A gelatinous colossus, master of swarms of slimes. He crushes everything in his path, slowly but surely.",
  },
  "albal-1": {
    title: "Albal",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 2615, z: 3825 },
    drops: ["N/A"],
    description: "A lone wolf with icy silver eyes. Its passage leaves a mist and silence.",
  },
  "albal-2": {
    title: "Albal",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 2510, z: 3955 },
    drops: ["N/A"],
    description: "A lone wolf with icy silver eyes. Its passage leaves a mist and silence.",
  },
  "albal-3": {
    title: "Albal",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 2390, z: 3820 },
    drops: ["N/A"],
    description: "A lone wolf with icy silver eyes. Its passage leaves a mist and silence.",
  },
  "nasgul-underground": {
    title: "Nasgul",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 2827, z: 4235 },
    drops: ["N/A"],
    description: "A cursed entity emerging from ancient darkness, it prowls, invisible, ready to tear the souls of the living.",
    underground: true
  },
  "narax-cursed-skeleton-underground": {
    title: "Narax Cursed Skeleton",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 2720, z: 4320 },
    drops: ["N/A"],
    description: "A cursed entity emerging from ancient darkness, it prowls, invisible, ready to tear apart the souls of the living.",
    underground: true
  },
  "ice-bear": {
    title: "Ice Bear",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 4000, z: 1995 },
    drops: ["N/A"],
    description: "Born in the coldest caves of the mountains, the Ice Bear embodies the brute force of the North. Its roar makes the air shiver, and its icy breath freezes everything in its path.",
  },
  "kazor": {
    title: "Kazor",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 2440, z: 945 },
    drops: ["N/A"],
    description: "Kazor uses erratic leaps and high burst phases, demanding coordinated interrupts from the party.",
  },
  "illfang-lord-kobold": {
    title: "Illfang, Lord Kobold",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 0, z: -10 },
    drops: ["N/A"],
    description: "The iconic first-floor raid tyrant, infamous for sudden weapon swaps and punishing final-phase aggression.",
  },
  "pricilia-underground": {
    title: "Pricilia",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1230, z: 1090 },
    drops: ["N/A"],
    description: "An ancient and cunning creature, Pricilia weaves her webs in the forgotten corners of the darkest forests. Its prey never sees death... only his glowing eyes.",
    underground: true
  },
  "yula-underground": {
    title: "Yula",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1100, z: 1215 },
    drops: ["N/A"],
    description: "Lurking in the damp darkness of the dungeon, Yula is a spider feared by adventurers. Its sharp legs and glowing eyes inspire terror in anyone who crosses its path.",
    underground: true
  },
  "kamilia-underground": {
    title: "Kamilia",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 985, z: 1235 },
    drops: ["N/A"],
    description: "Silent in the heart of the dungeon, Kamilia weaves invisible traps in the shadows. Its bite injects paralyzing venom, leaving its prey conscious, but unable to flee.",
    underground: true
  },
  "jira-underground": {
    title: "Jira",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1190, z: 1395 },
    drops: ["N/A"],
    description: "A silent creature lurking between the canvases, Jira watches every corner of the dungeon. Faster than lightning, she strikes without warning, leaving behind only silence... and bloody webs.",
    underground: true
  },
  "vyrmos-underground": {
    title: "Vyrmos",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 4250, z: 3845 },
    drops: ["N/A"],
    description: "A creeping entity born from the mines of Geldorak, Vyrmos soaks up spores and damp earth. His skin is covered in living foam, and his breath corrupts everything he touches.",
    underground: true
  },
  "tornak-underground": {
    title: "Tornak",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 4300, z: 3960 },
    drops: ["N/A"],
    description: "Massive and wild, this creature watches over the forest. She repels intruders with devastating punches. No words, only the brute force of nature.",
    underground: true
  },
  "nymbrea-underground": {
    title: "Nymbrea",
    type: "Boss",
    category: "bossSpawns",
    floor: "floor1",
    coords: { x: 1410, z: 2130 },
    drops: ["N/A"],
    description: "A mythical snake sliding between deep currents, Nymbrea embodies the grace and treachery of calm waters. Its scales sparkle like cursed pearls, and its hypnotic gaze draws the unwary towards the abyss.",
    underground: true
  }
};

const MOB_AREAS = [
  {
    id: "vallhat-mobs",
    title: "Vallhat",
    floor: "floor1",
    fill: "rgba(74, 191, 102, 0.26)",
    stroke: "#65d07e",
    corners: [
      { x: 128, z: 2773 },
      { x: 292, z: 2679 },
      { x: 501, z: 2700 },
      { x: 629, z: 2824 },
      { x: 584, z: 3144 },
      { x: 468, z: 3315 },
      { x: 261, z: 3378 }
    ]
  },
  {
    id: "swamp-putride-mobs",
    title: "Swamp Putride",
    floor: "floor1",
    fill: "rgba(146, 86, 56, 0.30)",
    stroke: "#da8d64",
    corners: [
      { x: 1013, z: 2875 },
      { x: 1603, z: 2800 },
      { x: 1706, z: 3180 },
      { x: 1036, z: 3276 }
    ]
  },
  {
    id: "wild-boar-zone",
    title: "Wild Boar Zone",
    floor: "floor1",
    fill: "rgba(98, 98, 196, 0.28)",
    stroke: "#8da0ff",
    corners: [
      { x: 1635, z: 3627 },
      { x: 1804, z: 3465 },
      { x: 1924, z: 3448 },
      { x: 2022, z: 3589 },
      { x: 1992, z: 3629 },
      { x: 1882, z: 3590 }
    ]
  },
  {
    id: "valley-of-wolves-mobs",
    title: "Valley of Wolves",
    floor: "floor1",
    fill: "rgba(243, 223, 120, 0.25)",
    stroke: "#fff2b5",
    corners: [
      { x: 2478, z: 3649 },
      { x: 2371, z: 3890 },
      { x: 2469, z: 3995 },
      { x: 2713, z: 3858 },
      { x: 2637, z: 3657 }
    ]
  },
  {
    id: "cursed-ruins",
    title: "Cursed Ruins",
    floor: "floor1",
    fill: "rgba(240, 167, 60, 0.28)",
    stroke: "#ffd074",
    corners: [
      { x: 2767, z: 4357 },
      { x: 2770, z: 4490 },
      { x: 2913, z: 4500 },
      { x: 2910, z: 4372 }
    ]
  },
  {
    id: "ika-archipelago-mobs",
    title: "Ika Archipelago",
    floor: "floor1",
    fill: "rgba(84, 156, 236, 0.25)",
    stroke: "#80beff",
    corners: [
      { x: 3234, z: 3994 },
      { x: 3186, z: 4089 },
      { x: 3217, z: 4191 },
      { x: 3370, z: 4195 },
      { x: 3431, z: 4143 },
      { x: 3411, z: 4021 }
    ]
  },
  {
    id: "mizunari-fields",
    title: "Mizunari Fields",
    floor: "floor1",
    fill: "rgba(176, 206, 88, 0.28)",
    stroke: "#d5f079",
    corners: [
      { x: 3375, z: 3680 },
      { x: 3293, z: 3717 },
      { x: 3363, z: 3822 },
      { x: 3444, z: 3764 }
    ]
  },
  {
    id: "geldorak-mine-mobs",
    title: "Geldorak Mine",
    floor: "floor1",
    fill: "rgba(162, 207, 255, 0.24)",
    stroke: "#e2f3ff",
    corners: [
      { x: 3954, z: 3820 },
      { x: 4053, z: 4100 },
      { x: 4384, z: 3870 }
    ]
  },
  {
    id: "snow-citadel-mobs",
    title: "Snow Citadel",
    floor: "floor1",
    fill: "rgba(162, 207, 255, 0.24)",
    stroke: "#e2f3ff",
    corners: [
      { x: 3911, z: 1943 },
      { x: 3912, z: 2005 },
      { x: 4021, z: 1999 },
      { x: 4023, z: 1929 }
    ]
  },
  {
    id: "wild-boar-meadow",
    title: "Wild Boar Meadow",
    floor: "floor1",
    fill: "rgba(98, 98, 196, 0.28)",
    stroke: "#8da0ff",
    corners: [
      { x: 2606, z: 1970 },
      { x: 2582, z: 2133 },
      { x: 2797, z: 2060 }
    ]
  },
  {
    id: "lake-virelune",
    title: "Lake Virelune",
    floor: "floor1",
    fill: "rgba(162, 207, 255, 0.24)",
    stroke: "#e2f3ff",
    corners: [
      { x: 1389, z: 1945 },
      { x: 1298, z: 2029 },
      { x: 1425, z: 2121 },
      { x: 1482, z: 2010 }
    ]
  },
  {
    id: "tolbana-mountains",
    title: "Tolbana Mountains",
    floor: "floor1",
    fill: "rgba(191, 153, 84, 0.28)",
    stroke: "#e0bc7c",
    corners: [
      { x: 4174, z: 1192 },
      { x: 4057, z: 1124 },
      { x: 4149, z: 960 },
      { x: 4267, z: 1041 }
    ]
  },
  {
    id: "arakh-nol-mobs",
    title: "Arakh'Nol",
    floor: "floor1",
    fill: "rgba(162, 207, 255, 0.24)",
    stroke: "#e2f3ff",
    corners: [
      { x: 1129, z: 1120 },
      { x: 1075, z: 1188 },
      { x: 1213, z: 1291 },
      { x: 1147, z: 1361 },
      { x: 1052, z: 1692 },
      { x: 1227, z: 1677 },
      { x: 1560, z: 1414 },
      { x: 1492, z: 1150 }
    ]
  }
];

